name: Add Comment to PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  add-comment:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Add Comment
      env:
        GITHUB_TOKEN: ${{ secrets.PR_COMMENT_SECRET }}
      run: |
        owner=$(echo '${{github.repository_owner}}')
        repo=$(echo '${{github.repository}}')
        pr_number=$(echo '${{github.event.number}}')
        curl -X POST https://api.github.com/repos/$owner/$repo/issues/$pr_number/comments -H 'Authorization: token ${{secrets.PR_COMMENT_SECRET}}' -d '{"body":"PR builder started."}'
    - uses: actions/checkout@v2

