name: Add Comment to PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  add-comment:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Add Comment
      env:
        GITHUB_TOKEN: ${{ secrets.PR_COMMENT }}
      run: |
        owner=$(echo '${{github.event.inputs.pr}}' | cut -d "/" -f 4)
        repo=$(echo '${{github.event.inputs.pr}}' | cut -d "/" -f 5)
        pr_number=$(echo '${{github.event.inputs.pr}}' | cut -d "/" -f 7)
        curl -X POST https://api.github.com/repos/$owner/$repo/issues/$pr_number/comments -H 'Authorization: token ${{secrets.PR_COMMENT}}' -d '{"body":"PR builder started."}'
    - uses: actions/checkout@v2

